# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops
# ignoreLASTEXITCODE: true -->we use Write-Error instead - better log output

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
   .\build.ps1
  displayName: 'Build'
  failOnStderr: true
  ignoreLASTEXITCODE: true 
- powershell: |
   Invoke-Pester -Script .\tests -OutputFile $(System.DefaultWorkingDirectory)\tests.testresults.xml -OutputFormat NUnitXML
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '*testresults.xml'    
